name: Seed DB (manual)

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run seed
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}  # put your Atlas URI in repo Secrets
